### ISSUE TITLE
NW 013.0-rc1 Uncaught TypeError: Cannot read property 'requireNwGui' of undefined

### ISSUE THREAD

**Issue by owen-hong** [edjafarov/node-webkit-updater#104]
In NW 0.13.0-rc1,Uncaught TypeError: Cannot read property 'requireNwGui' of undefined

You need delet "var gui = global.window.nwDispatcher.requireNwGui();"

**Comment by gaowenbo** [comment]
I have the same problem.

**Comment by adam-lynch** [comment]
Fixed by #98. Thanks!
