### ISSUE TITLE
Uncaught TypeError: Cannot read property 'requireNwGui' of undefined

### ISSUE THREAD

**Issue by bansalvks** [edjafarov/node-webkit-updater#108]
Node SDK Version : nwjs-sdk-v0.13.0-beta1-win-x64

Platform: Windows 8.1

Application crashing on  
`var gui = global.window.nwDispatcher.requireNwGui();`

Error:
`Uncaught TypeError: Cannot read property 'requireNwGui' of undefined`

**Comment by datnordstrom** [comment]
I changed mine to:
`var gui = window.require('nw.gui');`

and it worked for me.

**Comment by adam-lynch** [comment]
Fixed by #98. Thanks!
