### ISSUE TITLE
Unable to copy downloaded app updates from temp path to app path

### ISSUE THREAD

**Issue by Saravanan90** [edjafarov/node-webkit-updater#112]
- As per the existing update workflow, New app version can be copied from temp path to app path only after running the app from temp path.
- There is no way to copy the app updates from temp path to app path without running the app from temp path.

Cons of this approach:
- After an app update is downloaded and unpacked, user confirmation is required to install the updates.
- If the user accepts to install, runInstaller is called which runs the app from temp path and install is called which copies the current running application to app path.
- In case if user doesn't confirm, there should be way to copy the app updates from temp path to app path on app quit, so that the next time when user runs the app, the updated app runs.

Please let know if there is any API which can be used to achieve this.

**Comment by Saravanan90** [comment]
Can somebody help me on this issue?

**Comment by adam-lynch** [comment]
Hey.

That's just how this module works. I don't think it's possible to achieve what you want. For example, you can't delete the current app executable while it's running (on Windows, at least).

>After an app update is downloaded and unpacked, user confirmation is required to install the updates.

No, you could trigger this programmatically once the update is ready. It's not required to have the user confirm the update. I wouldn't advise it though as it's not good UX to interrupt the user.

>If the user accepts to install, runInstaller is called which runs the app from temp path and install is called which copies the current running application to app path.

Yeah, that's how it has to work.

>In case if user doesn't confirm, there should be way to copy the app updates from temp path to app path on app quit, so that the next time when user runs the app, the updated app runs.

This isn't really possible. The user can kill your app in a way that it just dies, so you won't be able to run any code. Even if the user clicks a button in your app to quit it, you can't delete the running executable as I mentioned already. Also, it would be a bit weird if the user clicked a button to quit your app and it disappears but it's still really running in the background, copying files around. Imagine if you quit the app and notice it's still visible in Task Manager / Activity Monitor. Or imagine if you quit the app, then try to shut down/restart your machine and it complained that the app is running.

OK so essentially you don't want users to ignore your update (and you shouldn't interrupt them and update like I said). I understand, you don't want users stuck on old versions out there. I suggest that when an update is ready, let the user know, and if they ignore it, store it in localStorage (or something like that) that an update is ready. Every time your app starts up and it's not in the middle of the existing update flow (i.e. if `process.argv` is empty) and the property in localStorage is there indicating there's an update ready, apply the update. So basically if there's an update and the user ignores it, the update will be forced the next time they launch the app.

On top of that, if there's an update and the user ignores it, you could apply the update when the app/machine has been idle for a certain amount of time. You could detect this with [node-afk](https://github.com/teamwork/node-afk) for example. You need to consider UX though again. You'll need to make sure though that the app goes back to the same screen and state when it finishes updating as it was before the update was started.

I hope this clears up some stuff 😄. Let me know if it doesn't.
