### ISSUE TITLE
Request to relocate repo to NW Utils

### ISSUE THREAD

**Issue by ayushmxn** [edjafarov/node-webkit-updater#124]
Hi @edjafarov,

I'm part of a GitHub org called [NW Utils](https://github.com/nwutils). I'm trying to consolidate NW tooling so it's easier to find useful projects and give much needed life to stagnant ones. I also think this would be a great opportunity to exchange ideas and learn new things. Let me know what you think and if you’d be willing to.

Best Regards
Ayushman

**Comment by ayushmxn** [comment]
@adam-lynch I noticed that you made the latest release. I wasn't able to get in touch with @edjafarov.

**Comment by adam-lynch** [comment]
I don't have the permissions to move the repo. Even if I did, I'd prefer to ask @edjafarov. Sorry
