### ISSUE TITLE
Adding extra argument for restart

### ISSUE THREAD

**Issue by cristianfraser** [edjafarov/node-webkit-updater#71]
On this step:

              upd.runInstaller newAppPath, [
                upd.getAppPath()
                upd.getAppExec()
                "update"
              ], {}

I'd like to add an extra argument to know on startup if the app is being updated or not, as opposed to just checking the length of argv. But adding an extra argument breaks the update, and upd.install/upd.run won't complete.

Also, I'm trying this on OSX meanwhile, and earlier I set the "update" argument first:

              upd.runInstaller newAppPath, [
                "update"
                upd.getAppPath()
                upd.getAppExec()
              ], {}

And this broke the update by recursively adding an "update" folder into the "app.nw" inside my Application.app with the same content than Application.app. `upd.install` and `upd.run` are receiving the same `copyPath` and `execPath` as before when it worked, but adding the extra "update" breaks it.

**Comment by adam-lynch** [comment]
I could be wrong but this extra argument might be being intercepted by NW.js / Chrome which then crashes / fails to start for some reason. I think I tried this quickly before but moved on once it failed. That's as much as I know right now tbh. @edjafarov?

**Comment by cristianfraser** [comment]
Nvm about the first case, I changed something in `updater.js` trying to fix the second case.

Soo, adding an extra argument before the paths still breaks the update (by recursively creating a new folder inside `app.nw`, at least on OSX), but putting the extra argument after the paths works.

**Comment by adam-lynch** [comment]
Just to be safe now, I'll point out what might be obvious... you did change [these lines]:

```
    copyPath = gui.App.argv[0];
    execPath = gui.App.argv[1];
```

to:

```
    copyPath = gui.App.argv[0];
    execPath = gui.App.argv[1];
```

right?

**Comment by adam-lynch** [comment]
Woops, typo... just updated my last comment now

**Comment by cristianfraser** [comment]
God, I did... and I would've sworn I did before I started fiddling with `updater.js`... but I didn`t. So, both ways work and this is closed.

Thanks for replying quickly though, great tool :)

**Comment by adam-lynch** [comment]
Great :+1:
