### ISSUE TITLE
Why is NW required....

### ISSUE THREAD

**Issue by brian-mann** [edjafarov/node-webkit-updater#72]
Specifically this line: https://github.com/edjafarov/node-webkit-updater/blob/master/app/updater.js#L10

What's the reasoning for this?  It makes it difficult to unit test our own updater code since I basically have to stub out the NW object to get it to work.

**Comment by adam-lynch** [comment]
Must be a leftover from when `gui.Shell.openItem` was used in `.run()`. Thanks for pointing it out.
