### ISSUE TITLE
Can I keep some custom setting in new version?

### ISSUE THREAD

**Issue by Michael00767** [edjafarov/node-webkit-updater#80]

**Comment by Michael00767** [comment]
I store some information in a setting file.The setting file will be replace after update.Is any possible to keep setting file after update?

**Comment by adam-lynch** [comment]
Store it somewhere else, like [`gui.App.dataPath`](https://github.com/nwjs/nw.js/wiki/App#datapath).

**Comment by Michael00767** [comment]
gui.App.dataPath is a good choose ,tks @adam-lynch
