### ISSUE TITLE
Preserving localStorage on app update?

### ISSUE THREAD

**Issue by xingped** [edjafarov/node-webkit-updater#82]
Is localStorage preserved when your app is updated? If not, is there a way/strategy to preserve localStorage and transfer it to the new app?

**Comment by hermwong** [comment]
The localStorage is preserved when your app is updated.

**Comment by adam-lynch** [comment]
Unless you're somehow deleting the directory where it's stored. Doubt it though. This might happen if your new update has a different as well though.

**Comment by jhaslowh** [comment]
Whenever my app updates, everything in the directory is deleted and the new updated app files are placed in the directory. Is there a way to make it only delete the app files being replaced? 

For reference, this is happening on Windows 10 (64bit)

**Comment by adam-lynch** [comment]
@jhaslowh Not with this updater. Yet, at least; see #63.
