### ISSUE TITLE
Some Forks Seem Critical. Repo Still Active?

### ISSUE THREAD

**Issue by TomAshley303** [edjafarov/node-webkit-updater#95]
There are some forks with security and bug fixes. Was wondering if they've been patched here. I also see a lot of issues that haven't been answered and am wondering if this is still maintained. This is very needed and I can't find any alternatives.

**Comment by Aufree** [comment]
+1

**Comment by adam-lynch** [comment]
@TomAshley303 It's been maintained basically just by me at this stage I think. It's actively used in production though, it's fine for usage. Any help is appreciated.
