### ISSUE TITLE
Unzip.exe not compatible with 64-bit versions of windows

### ISSUE THREAD

**Issue by piotrromanowski** [edjafarov/node-webkit-updater#97]
When trying to use the updater on my Windows 10 machine I get the following error 

"C:\..\tools\unzip.exe" cannot start or run due to incompatibility with 64-bit versions of Windows

**Comment by piotrromanowski** [comment]
Fixed the problem by using node Adm-Zip instead of the zip.exe on my fork
https://github.com/piotrromanowski/node-webkit-updater

**Comment by adam-lynch** [comment]
I don't understand it's possible there could be an incompatibility with 64-bit Windows. I'm on 64-bit Windows myself too.
